---
title: "Foodweb restauracao"
author: "Carine Emer"
date: "13/11/2018"
output: word_document
---

#######################################################################
Dataset Rafael Domingos and Gislene Ganade - UFRN
Foodwebs plant-herbivore in restored communities

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, echo=T, include = F}
# Set the working directory
setwd("~/Dropbox/Rafael restauracao/Insect_plant restoration/New matrices")
#knitr::opts_knit$set(root.dir = "setwd("~/Dropbox/Rafael restauracao")
```


```{r load packages, include = F, echo = T}
# load packages
library(bipartite)
library(vegan)
library(reshape2)
library(igraph)
library(networkD3)
library(reshape2)
library(dplyr)
library(tidyverse)
library(data.table)
```


```{r input data}
y2017<-read.csv("Matriz_2017.csv", head=T,row.names=1)
y2018<-read.csv("Matriz_2018.csv", head=T,row.names=1)

##### function to input multiples .csv at once

###################### --------------------------- Diversity 2017
setwd("~/Dropbox/Rafael restauracao/Data/New matrices")
# assuming your working directory is the folder with the CSVs
myfiles <- dir(pattern = "\\.(csv|CSV)$", full.names = TRUE) # get filenames and paths
new_data<-lapply(myfiles, read.csv, row.names=1, header = T)# read data from files, quickly
head(new_data[[1]]) # validate file reading
names(new_data) <- myfiles # assign names to list item


###################### --------------------------- Diversity 2018
setwd("~/Dropbox/Rafael restauracao/Data/Matrizes 2018")
myfiles18 <- dir(pattern = "\\.(csv|CSV)$", full.names = TRUE) # get filenames and paths
d2018<-lapply(myfiles18, read.csv, row.names=1, header = T)# read data from files, quickly
head(d2018[[1]]) # validate file reading
names(d2018) <- myfiles18 # assign names to list item

###################### ---------------------------Plots 2017
setwd("~/Dropbox/Rafael restauracao/Data/Matrizes 2017/Matrizes por Plot")
# assuming your working directory is the folder with the CSVs
myfiles <- dir(pattern = "\\.(csv|CSV)$", full.names = TRUE) # get filenames and paths
p2017<-lapply(myfiles, read.csv, row.names=1, header = T)# read data from files, quickly
head(p2017[[1]]) # validate file reading
names(p2017) <- myfiles # assign names to list item


###################### --------------------------- Plots 2018
setwd("~/Dropbox/Rafael restauracao/Data/Matrizes 2018/Matrizes por Plot")
myfiles18 <- dir(pattern = "\\.(csv|CSV)$", full.names = TRUE) # get filenames and paths
p2018<-lapply(myfiles18, read.csv, row.names=1, header = T)# read data from files, quickly
head(p2018[[1]]) # validate file reading
names(p2018) <- myfiles18 # assign names to list item

str(p)

```

#################################
Drawing networks
#################################

```{r plot networks bipartite}

plot2017<-plotweb(y2017,  ## set overall parameters 
              text.rot=c(90), labsize=1,arrow="down.center",
              y.width.low=0.05,y.width.high=0.05, ybig=1.8, low.y=1.2, high.y=2,
              high.spacing=.01, low.spacing=0.01,
              # shorter labels
              #high.lablength=3, low.lablength=0, 
              ### check the method if you prefer
                   method="cca", 
              ### set colors
                  col.low="green", col.high="yellow", col.interaction = "grey80")

plot2018<-plotweb(y2018,  ## set overall parameters 
              text.rot=c(90), labsize=1,arrow="down.center",
              y.width.low=0.05,y.width.high=0.05, ybig=1.8, low.y=1.2, high.y=2,
              high.spacing=.01, low.spacing=0.01,
              # shorter labels
              #high.lablength=3, low.lablength=0, 
              ### check the method if you prefer
                   method="cca", 
              ### set colors
                  col.low="green", col.high="yellow", col.interaction = "grey80")
```


```{r plot igraph}
guilds2017<-read.csv("data2017.csv", head=T)
guilds2018<-read.csv("data2018.csv", head=T)

###################
#############################################2018
#Transform the previous bipartite object into an igraph object
net2 = cbind.data.frame(reference=row.names(y2018),y2018)
str(net2)
netlist = melt(net2, na.rm = T)
colnames(netlist) = c("rows", "columns", "weight")
netlist[,1]=as.character(paste(netlist[,1]))
netlist[,2]=as.character(paste(netlist[,2]))
netlist2 <- subset(netlist, weight > 0)
nodes <- unique(data.frame(nodes = c(netlist2[,1], netlist2[,2])))
head(nodes)
links = netlist2
g <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
class(g)

#Check the main properties of the igraph object
V(g)
E(g)

#ordering dataframes so that the order of species list matches the order of species in graph g
guild <- guilds2018[order(match(guilds2018$species, V(g)$name)),] 

## to create a vector for guild
V(g)$guild=as.character(guild$guild)
V(g)$shape=V(g)$guild
V(g)$shape[V(g)$guild=="insect"]="circle"
V(g)$shape[V(g)$guild=="plant"]="square"

## to create a vector for guild
V(g)$guild=as.character(guild$guild)
V(g)$color=V(g)$guild
V(g)$color[V(g)$guild=="insect"]="red"
V(g)$color[V(g)$guild=="plant"]="green"

## to create a vector for labels
V(g)$label=as.character(guild$id)

plot(g,
     # Set the drawing mode
     # This package contains several drawing methods; try them!
     layout=layout_with_graphopt,
     # Set title
     main='2018',
    # Set node attributes
     vertex.shape=V(g)$shape,
     vertex.size = 6,
     vertex.color = V(g)$color,
     # Set link colors
     edge.color = "lightblue",
     # Set link curvature from 0 to 1
     edge.curved=0.3,
     # Set nodes labels
     #vertex.label.dist=200,
     vertex.label.color='black',
     vertex.label.font=1,
     vertex.label=V(g)$label,
     vertex.label.cex=0.5
)


#################
#########################2017
#Transform into an igraph object
net2 = cbind.data.frame(reference=row.names(y2017),y2017)
str(net2)
netlist = melt(net2, na.rm = T)
colnames(netlist) = c("rows", "columns", "weight")
netlist[,1]=as.character(paste(netlist[,1]))
netlist[,2]=as.character(paste(netlist[,2]))
netlist2 <- subset(netlist, weight > 0)
nodes <- unique(data.frame(nodes = c(netlist2[,1], netlist2[,2])))
head(nodes)
links = netlist2
g17 <- graph_from_data_frame(d=links, vertices=nodes, directed=F) 
class(g17)

#Check the main properties of the igraph object
V(g17)
E(g17)

#ordering dataframes so that the order of species list matches the order of species in graph g
guild <- guilds2017[order(match(guilds2017$species, V(g17)$name)),] 

## to create a vector for guild
V(g17)$guild=as.character(guild$guild)
V(g17)$shape=V(g17)$guild
V(g17)$shape[V(g17)$guild=="insect"]="circle"
V(g17)$shape[V(g17)$guild=="plant"]="square"

## to create a vector for guild
V(g17)$guild=as.character(guild$guild)
V(g17)$color=V(g17)$guild
V(g17)$color[V(g17)$guild=="insect"]="red"
V(g17)$color[V(g17)$guild=="plant"]="green"

## to create a vector for labels
V(g17)$label=as.character(guild$id)
## to create a vector for node size

zVar <- (guild$k - min(guild$k)) / (max(guild$k)-min(guild$k))

                                        
V(g17)$size=zVar*10


plot(g17,
     # Set the drawing mode
     # This package contains several drawing methods; try them!
     #layout=layout_nicely(g17),
       layout=layout_nicely,
     # Set title
     main='2017',
     # Set node attributes
     vertex.shape=V(g17)$shape,
     vertex.size = V(g17)$size,
     vertex.color = V(g17)$color,
     # Set link colors
     edge.color = "lightblue",
     # Set link curvature from 0 to 1
     edge.curved=0.3,
     # Set nodes labels
     #vertex.label.dist=1,
     vertex.label.color='black',
     vertex.label.font=3,
     vertex.label=V(g17)$label,
     vertex.label.cex=.6
)
```


```{r plot network3D}
##### network3D
## transform to edgelist
m1<-melt(y2017) 
## select only interactions =1
m2 <- subset(m1, value>0) 
g=graph.data.frame(m2,directed=FALSE) # sets the graph framework

####  SIMPLE  NETWORK
simpleNetwork(m2)


### OR
# Find group membership
wt <- cluster_walktrap(g, steps = 16)
members <- membership(wt)
# Convert igraph to list for networkD3
sj_list <- igraph_to_networkD3(g, group = members)

# Plot as a forceDirected Network
ntw<-forceNetwork(Links = sj_list$links, Nodes = sj_list$nodes, Source = 'source',
          Target = 'target', NodeID = 'name', Group = 'group',
              zoom = TRUE, linkDistance = 0.01,opacity=1.2)
 ,          colourScale = "d3.scale.category20f()")
ntw
saveNetwork(ntw, 'ntw_2017.html', selfcontained =T)

#### 2018
## transform to edgelist
m1<-melt(y2018) 
## select only interactions =1
m2 <- subset(m1, value>0) 
g=graph.data.frame(m2,directed=FALSE) # sets the graph framework

####  SIMPLE  NETWORK
simpleNetwork(m2)


### OR
# Find group membership
wt <- cluster_walktrap(g, steps = 16)
members <- membership(wt)
# Convert igraph to list for networkD3
sj_list <- igraph_to_networkD3(g, group = members)

# Plot as a forceDirected Network
ntw<-forceNetwork(Links = sj_list$links, Nodes = sj_list$nodes, Source = 'source',
          Target = 'target', NodeID = 'name', Group = 'group',
              zoom = TRUE, linkDistance = 1,opacity=1.2)
 ,          colourScale = "d3.scale.category20f()")
ntw
saveNetwork(ntw, 'ntw_2018.html', selfcontained =T)

```

# sets the graph framework
  g=graph.data.frame(m2,directed=FALSE) 
n3D<-simpleNetwork(m2)
n3D
saveNetwork(n3D, file = "y2017.html") ### save network as html


```{r connectance}
############################## CONNECTANCE #####################
obs_c_2017<-networklevel(y2017, index="connectance")

# Set Null Model
  null <-nullmodel(y2017, N=100, method=3) 
  null1 <-sapply (X=null, FUN=networklevel, index="connectance") 
  means_null1 <- apply (X=cbind(null1),MARGIN=2, FUN=mean, na.rm=T)  
  sd.means_null1 <- apply(X=cbind(null1), MARGIN=2, FUN=sd, na.rm=T)
  z_score<-(obs_c_2017-means_null1)/sd.means_null1
  z_score
  p_value<-sum(null1>= obs_c_2017)/1000 # valor de p
  p_value

plot(density(null1), lwd=2, xlim=c(0, 1))
abline(v=obs_c_2017, col="red", lwd=1)


### 2018

obs_c_2018<-networklevel(y2018, index="connectance")

# Set Null Model
  null <-nullmodel(y2018, N=100, method=3) 
  null1 <-sapply (X=null, FUN=networklevel, index="connectance") 
  means_null1 <- apply (X=cbind(null1),MARGIN=2, FUN=mean, na.rm=T)  
  sd.means_null1 <- apply(X=cbind(null1), MARGIN=2, FUN=sd, na.rm=T)
  z_score<-(obs_c_2018-means_null1)/sd.means_null1
  z_score
  p_value<-sum(null1>= obs_c_2018)/1000 # valor de p
  p_value

plot(density(null1), lwd=2, xlim=c(0, 1))
abline(v=obs_c_2018, col="red", lwd=1)

################### diversity plots
###d2017
results_c<-sapply (new_data, FUN=networklevel, index="connectance") 
###d2018
results_c2018<-sapply (d2018, FUN=networklevel, index="connectance") 
results_c<-cbind(results_c2017,results_c2018) #### need to 
results_c


```

```{r links per species and partner diversity}
### --------------------------------------- Diversity Plots --------------
###########
#######################links per species
results_lsp2017<-sapply (d2017, FUN=networklevel, index="links per species") 
###d2018
results_lsp2018<-sapply (d2018, FUN=networklevel, index="links per species") 
results_lsp<-cbind(results_lsp2017,results_lsp2018) #### 

### new data
links_sp<-sapply (new_data, FUN=networklevel, index="links per species") 

###########
##################partner diversity
results_pdiv2017<-sapply (d2017, FUN=networklevel, index="partner diversity")
results_pdiv2018<-sapply (d2018, FUN=networklevel, index="partner diversity") 
results_pdiv<-cbind(results_pdiv2017,results_pdiv2018) #### 


res_partdiv_newdata<-sapply (new_data, FUN=networklevel, index="partner diversity")
res_partdiv_newdata<-t(as.data.frame(res_partdiv_newdata))

res_metrics<-cbind(links_sp,res_partdiv_newdata)


###############
###########################connectance
connectance<-sapply (new_data, FUN=networklevel, index="connectance")

res_metrics1<-cbind(res_metrics,connectance)

head(res_metrics1)

###############
########################### weigthed nestedness
wnodf<-sapply (new_data, FUN=networklevel, index="weighted nestedness")

res_metrics2<-cbind(res_metrics1,wnodf)

head(res_metrics2)

###############
########################### weigthed nestedness
mod<-sapply (new_data, FUN=computeModules)
modularity <- sapply(mod, function(x) x@likelihood)


res_metrics3<-cbind(res_metrics2,modularity)

head(res_metrics3)

write.csv(res_metrics3, "results_newdata.csv")


### --------------------------------------- Individual plots --------------
########### links per species
results_lsp2017p<-sapply (p2017, FUN=networklevel, index="links per species") 
###d2018
results_lsp2018p<-sapply (p2018, FUN=networklevel, index="links per species") 
results_lsp<-cbind(results_lsp2017p,results_lsp2018p) #### 

########### partner diversity
results_pdiv2017p<-sapply (p2017, FUN=networklevel, index="partner diversity")
results_pdiv2018p<-sapply (p2018, FUN=networklevel, index="partner diversity") 
results_pdiv<-cbind(results_pdiv2017p,results_pdiv2018p) #### 


#write.csv(results_lsp,"results_metrics.csv")
```


```{r nestedness}
########################## NESTEDNESS ########################## 
nested_2017<-networklevel(y2017, index = "weighted NODF")
nested_2017

#### Using the classical nullmodels for bipartite
## method 3 = vaznull
  null <-nullmodel(y2017, N=100, method=3) 
  null1 <-sapply (X=null, FUN=nested, method="NODF2") 
  means_null1 <- apply (X=cbind(null1),MARGIN=2, FUN=mean, na.rm=T)  
  sd.means_null1 <- apply(X=cbind(null1), MARGIN=2, FUN=sd, na.rm=T)
  z_score<-(nested_2017-means_null1)/sd.means_null1
  z_score
  p_value<-sum(null1>= nested_2017)/1000 # valor de p
  p_value

plot(density(null1), lwd=2, xlim=c(0, 70))
abline(v=nested_2017, col="red", lwd=1)


####### 2018
nested_2018<-networklevel(y2018, index = "weighted NODF")
nested_2018

  null <-nullmodel(y2018, N=100, method=3) 
  null1 <-sapply (X=null, FUN=nested, method="NODF2") 
  means_null1 <- apply (X=cbind(null1),MARGIN=2, FUN=mean, na.rm=T)  
  sd.means_null1 <- apply(X=cbind(null1), MARGIN=2, FUN=sd, na.rm=T)
  z_score<-(nested_2018-means_null1)/sd.means_null1
  z_score
  p_value<-sum(null1>= nested_2018)/1000 # valor de p
  p_value

plot(density(null1), lwd=2, xlim=c(0, 70))
abline(v=nested_2018, col="red", lwd=1)


```

```{r modularity}
######################### MODULARITY ########################## 
m_2018<-computeModules(y2018)
m_2018
# Check the components of each module
  #printoutModuleInformation(m_2017)
  #plotModuleWeb(m_2017)

# Set Null Model
  nulls <- nullmodel(y2017, N=100, method=3) 
  modules.nulls <- sapply(nulls, computeModules)
  like.nulls <- sapply(modules.nulls, function(x) x@likelihood)
  z <- (m_2017@likelihood - mean(like.nulls))/sd(like.nulls)
  z
  p <- 2*pnorm(-abs(z))
  plot(density(like.nulls), lwd=2, xlim=c(0, .8))
  abline(v=m_2017@likelihood, col="red", lwd=1)
 
  
######2018  
m_2018<-computeModules(y2018)
m_2018
# Check the components of each module
  printoutModuleInformation(m_2018)
  plotModuleWeb(m_2018)

# Set Null Model
  nulls <- nullmodel(y2018, N=100, method=3) 
  modules.nulls <- sapply(nulls, computeModules)
  like.nulls <- sapply(modules.nulls, function(x) x@likelihood)
  z <- (m_2018@likelihood - mean(like.nulls))/sd(like.nulls)
  z
  p <- 2*pnorm(-abs(z))
  plot(density(like.nulls), lwd=2, xlim=c(0, .8))
  abline(v=m_2018@likelihood, col="red", lwd=1)  
  

save.image("insect_plant.RData")
```


## to test which species or interactions are most common between years??

```{r centrality}

k_2017_i<-specieslevel(y2017, index = "degree", level = 'higher' )
k_2017_p<-specieslevel(y2017, index = "degree", level = 'lower' )
k_2018_i<-specieslevel(y2018, index = "degree", level = "higher")
k_2018_p<-specieslevel(y2018, index = "degree", level = "lower")

write.csv(k_2017_i, "k_insects_2017.csv")
write.csv(k_2018_i, "k_insects_2018.csv")
write.csv(k_2017_p, "k_plants_2017.csv")
write.csv(k_2017_p, "k_plants_2018.csv")


k_2017div16_i<-specieslevel(new_data[[1]], index = "degree", level = 'higher' )
k_2017div2_i<-specieslevel(new_data[[2]], index = "degree", level = 'higher' )
k_2017div4_i<-specieslevel(new_data[[3]], index = "degree", level = 'higher' )
k_2017div8_i<-specieslevel(new_data[[4]], index = "degree", level = 'higher' )
write.csv(k_2017div16_i, "k_insects_2017div16.csv")
write.csv(k_2017div2_i, "k_insects_2017div2.csv")
write.csv(k_2017div4_i, "k_insects_2017div4.csv")
write.csv(k_2017div8_i, "k_insects_2017div8.csv")

########### Insects 2018 
k_2018div16_i<-specieslevel(new_data[[6]], index = "degree", level = 'higher' )
k_2018div2_i<-specieslevel(new_data[[7]], index = "degree", level = 'higher' )
k_2018div4_i<-specieslevel(new_data[[8]], index = "degree", level = 'higher' )
k_2018div8_i<-specieslevel(new_data[[9]], index = "degree", level = 'higher' )
write.csv(k_2018div16_i, "k_insects_2018div16.csv")
write.csv(k_2018div2_i, "k_insects_2018div2.csv")
write.csv(k_2018div4_i, "k_insects_2018div4.csv")
write.csv(k_2018div8_i, "k_insects_2018div8.csv")

############ PLANTS 2017
k_2017div16_p<-specieslevel(new_data[[1]], index = "degree", level = 'lower' )
k_2017div2_p<-specieslevel(new_data[[2]], index = "degree", level = 'lower' )
k_2017div4_p<-specieslevel(new_data[[3]], index = "degree", level = 'lower' )
k_2017div8_p<-specieslevel(new_data[[4]], index = "degree", level = 'lower' )
write.csv(k_2017div16_p, "k_plants_2017div16.csv")
write.csv(k_2017div2_p, "k_plants_2017div2.csv")
write.csv(k_2017div4_p, "k_plants_2017div4.csv")
write.csv(k_2017div8_p, "k_plants_2017div8.csv")

########### Plants 2018 
k_2018div16_p<-specieslevel(new_data[[6]], index = "degree", level = 'lower' )
k_2018div2_p<-specieslevel(new_data[[7]], index = "degree", level = 'lower' )
k_2018div4_p<-specieslevel(new_data[[8]], index = "degree", level = 'lower' )
k_2018div8_p<-specieslevel(new_data[[9]], index = "degree", level = 'lower' )
write.csv(k_2018div16_p, "k_plants_2018div16.csv")
write.csv(k_2018div2_p, "k_plants_2018div2.csv")
write.csv(k_2018div4_p, "k_plants_2018div4.csv")
write.csv(k_2018div8_p, "k_plants_2018div8.csv")




head(new_data[10])

```


```{r save RData}
save.image("restoration.RData")

```

